### ISSUE TITLE
running executable fail on wayland

### ISSUE THREAD

**Issue by yzn-h** [ElhamAryanpur/BlueEngine#13]
the error `thread 'main' panicked at 'Error in Surface::configure: requested format Bgra8UnormSrgb is not in list of supported formats: [Bgra8Unorm]', /home/yzn/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.2/src/backend/direct.rs:188:9`

**Comment by ElhamAryanpur** [comment]
@yzn-h can you now try and build? it should be fixed

**Comment by yzn-h** [comment]
![image](https://user-images.githubusercontent.com/63852512/168271811-00e0d6e6-adbb-4890-9683-3cb8ac21234c.png)
it is working 🔥

**Comment by ElhamAryanpur** [comment]
Awesome!!
