### ISSUE TITLE
That "Outdated" issue

### ISSUE THREAD

**Issue by werner291** [ElhamAryanpur/BlueEngine#7]
Hello (I'm Derg on Discord),

I see what's going on with the error message:

Resizing the window causes the swapchain to become outdated (specifically, `gfx_hal::window::OutOfDate` is the underlying error message).

I'm assuming that, sometime *after* you attempt to draw to the resized window, the event loop receives a `WindowEvent::Resized`, which causes the renderer to recreate the swapchain, and thus resolves the invalidation.

Once you remove that call to `resize` in response to the window resize vent, the `Outdated` error shows up every frame.

**Comment by ElhamAryanpur** [comment]
Hello. No i really did not... I didn't touch anything I swear!

**Comment by ElhamAryanpur** [comment]
DM me

**Comment by ElhamAryanpur** [comment]
This was fixed on [0.1.92](https://github.com/ElhamAryanpur/BlueEngine/commit/d53fd30a78c547344d8cfe03c2790108a5c9e023) version. Please test against that version and let me know if the problem still exist!
